package gr.hua.dit.ds.ds_lab_2024.entities;

public enum NotificationTask {
    VERIFY_ACCOUNT_FROM_USER,
    VERIFY_ACCOUNT_FROM_ADMIN,
    VERIFY_NEW_PROPERTY_FROM_OWNER,
    VERIFY_NEW_PROPERTY_FROM_ADMIN,
    VERIFY_APPLICATION_FROM_USER,
    VERIFY_APPLICATION_FROM_OWNER
}
